name: MiracleBlock
version: '${project.version}'
main: github.snugbrick.miracleblock.MiracleBlock
api-version: '1.16'
authors: [ MiracleUR ]
description: a rpg trying
website: https://github.com/snugbrick

depend: [ Citizens,ProtocolLib,SuperVanish ]
softdepend: [ PremiumVanish ]

commands:
  totemplateworld:
    description: "goto Temp World"

    usage: "/totemplateworld"

    permission: op

    permission-message: "你妹有op啊，执行不了啊awa"

  db-easy-sql:
    description: db-easy-sql

    usage: "/db-easy-sql"

    permission: op

    permission-message: "你妹有op啊，执行不了啊awa"

  get-miracle-item:
    description: get-miracle-item

    usage: "get-miracle-item"

    permission: ""

    permission-message: "/get-miracle-sword <miracle_item_key>"

  set-item-inlaid:
    description: set-item-inlaid

    usage: "set-item-inlaid"

    permission: ""

    permission-message: "/set-item-inlaid <miracle_sword_name> <miracle-Inlay-item>"

  miracle-entity-gen:
    description: miracle-entity-gen

    usage: "miracle-entity-gen"

    permission: ""

    permission-message: "/miracle-entity-gen <miracle-entity-name>"


permissions:
  op:
    default: op