name: MiracleBlock
version: '${project.version}'
main: github.snugbrick.miracleblock.MiracleBlock
api-version: '1.16'
authors: [ MiracleUR ]
description: a rpg trying
website: https://github.com/snugbrick

depend: [ Citizens,ProtocolLib,SuperVanish ]
softdepend: [ PremiumVanish ]

commands:
  totemplateworld:
    description: "goto Temp World"

    usage: "/totemplateworld"

    permission: op

    permission-message: "你妹有op啊，执行不了啊awa"

  db-easy-sql:
    description: db-easy-sql

    usage: "/db-easy-sql"

    permission: op

    permission-message: "你妹有op啊，执行不了啊awa"

  mb:
    description: MiraBlock Commands

    usage: "/mb <args0> <args1>"

    permission: ""

    permission-message: "/mb <args0> <args1>"

permissions:
  op:
    default: op